### ISSUE TITLE
Font Awesome Icons

### ISSUE THREAD

**Issue by shan8851** [codebushi/gatsby-starter-photon-v2#2]
When editing the default icons on section 2 only certain icons work, things like fa-js, fa-css3-alt and fa-npm display nothing. Others like fa-git, fa-github and more work fine. Any ideas?

Awesome site btw! Really love the design :)

**Comment by ChangoMan** [comment]
The font awesome version being used is Font Awesome 4.7.0, so not all icons are available. You can update your specific version for more icons.
